create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger as $$
begin new.updated_at = now(); return new; end; $$ language plpgsql set search_path = public;

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.suppliers (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  contact text, phone text, email text, notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.units (
  code text primary key,
  name text not null,
  created_at timestamptz not null default now()
);
create table public.app_users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  role text not null default 'operador',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);
create table public.products (
  id uuid primary key default gen_random_uuid(),
  code integer unique,
  description text not null,
  category_id uuid references public.categories(id) on delete set null,
  supplier_id uuid references public.suppliers(id) on delete set null,
  unit text not null default 'UN' references public.units(code),
  current_stock numeric not null default 0,
  avg_weekly_consumption numeric not null default 0,
  min_stock numeric not null default 0,
  desired_stock numeric not null default 0,
  coverage_weeks numeric,
  safety_stock numeric not null default 0,
  lead_time_days integer not null default 0,
  active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index on public.products (category_id);
create index on public.products (supplier_id);

create table public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  type text not null,
  quantity_before numeric not null,
  quantity_change numeric not null,
  quantity_after numeric not null,
  user_name text not null default 'Sistema',
  notes text,
  reference_type text,
  reference_id uuid,
  created_at timestamptz not null default now()
);
create index on public.stock_movements (product_id, created_at desc);

create table public.stock_counts (
  id uuid primary key default gen_random_uuid(),
  counted_at timestamptz not null default now(),
  user_name text not null default 'Sistema',
  status text not null default 'concluida',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.stock_count_items (
  id uuid primary key default gen_random_uuid(),
  count_id uuid not null references public.stock_counts(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  expected_quantity numeric not null default 0,
  counted_quantity numeric not null default 0,
  difference numeric not null default 0,
  notes text,
  created_at timestamptz not null default now()
);
create index on public.stock_count_items (count_id);

create table public.purchase_orders (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity unique,
  supplier_id uuid references public.suppliers(id) on delete set null,
  status text not null default 'rascunho',
  notes text,
  user_name text not null default 'Sistema',
  ordered_at timestamptz,
  received_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.purchase_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.purchase_orders(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  quantity numeric not null default 0,
  received_quantity numeric not null default 0,
  unit text not null default 'UN',
  notes text,
  created_at timestamptz not null default now()
);
create index on public.purchase_order_items (order_id);

create trigger t1 before update on public.categories for each row execute function public.set_updated_at();
create trigger t2 before update on public.suppliers for each row execute function public.set_updated_at();
create trigger t3 before update on public.products for each row execute function public.set_updated_at();
create trigger t4 before update on public.purchase_orders for each row execute function public.set_updated_at();
create trigger t5 before update on public.stock_counts for each row execute function public.set_updated_at();
create trigger t6 before update on public.app_users for each row execute function public.set_updated_at();

grant select, insert, update, delete on public.categories, public.suppliers, public.units, public.app_users, public.settings, public.products, public.stock_movements, public.stock_counts, public.stock_count_items, public.purchase_orders, public.purchase_order_items to anon, authenticated;
grant all on public.categories, public.suppliers, public.units, public.app_users, public.settings, public.products, public.stock_movements, public.stock_counts, public.stock_count_items, public.purchase_orders, public.purchase_order_items to service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

alter table public.categories enable row level security;
alter table public.suppliers enable row level security;
alter table public.units enable row level security;
alter table public.app_users enable row level security;
alter table public.settings enable row level security;
alter table public.products enable row level security;
alter table public.stock_movements enable row level security;
alter table public.stock_counts enable row level security;
alter table public.stock_count_items enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_items enable row level security;

create policy "open" on public.categories for all to anon, authenticated using (true) with check (true);
create policy "open" on public.suppliers for all to anon, authenticated using (true) with check (true);
create policy "open" on public.units for all to anon, authenticated using (true) with check (true);
create policy "open" on public.app_users for all to anon, authenticated using (true) with check (true);
create policy "open" on public.settings for all to anon, authenticated using (true) with check (true);
create policy "open" on public.products for all to anon, authenticated using (true) with check (true);
create policy "open" on public.stock_movements for all to anon, authenticated using (true) with check (true);
create policy "open" on public.stock_counts for all to anon, authenticated using (true) with check (true);
create policy "open" on public.stock_count_items for all to anon, authenticated using (true) with check (true);
create policy "open" on public.purchase_orders for all to anon, authenticated using (true) with check (true);
create policy "open" on public.purchase_order_items for all to anon, authenticated using (true) with check (true);

insert into public.units (code, name) values
('UN','Unidade'),('KG','Quilograma'),('CX','Caixa'),('L','Litro'),('PCT','Pacote'),('FD','Fardo'),('SC','Saco'),('BANDEJA','Bandeja'),('PORCAO','Porção'),('ROLO','Rolo');

insert into public.settings (key, value) values
('purchase_rules','{"coverage_weeks":1,"safety_margin_percent":0,"default_lead_time_days":0,"attention_threshold_percent":20,"formula":"desired"}'::jsonb);

insert into public.app_users (name, role) values ('Administrador','admin');

with raw(code, description, category, supplier, unit, stock, consumption) as (
  values
(1,'TAMPAS DE POTE','CONDIMENTOS E TEMPEROS','UP','UN',4000,825),(2,'SACO VINAGRETE','DESCARTÁVEIS','UP','UN',1000,2600),(3,'SACO TROCO','DESCARTÁVEIS','UP','UN',1000,1100),(4,'TAMPA M32','OUTROS','UP','UN',900,260),(5,'CALABRESA CHARQUE','CARNES','UP','KG',0,6.6),(6,'M65','OUTROS','UP','UN',400,400),(7,'H3','OUTROS','UP','UN',300,550),(8,'M32','OUTROS','UP','UN',300,260),(9,'M50','OUTROS','UP','UN',400,900),(10,'M500','OUTROS','UP','UN',300,400),(11,'TAMPA M500','OUTROS','UP','UN',250,400),(12,'POTE MAIONESE','DESCARTÁVEIS','UP','UN',50,825),(13,'H2','OUTROS','UP','UN',100,550),(14,'H5','OUTROS','DESCARTÁVEIS GBM','UN',50,275),(15,'GALETOS CORTADOS','CARNES','VAGNER GBM','UN',30,310),(16,'PRATO DESCARTAVEL','DESCARTÁVEIS','UP','UN',43,0),(17,'FEIJÃO TROPEIRO','ALIMENTOS','UP CEREAIS','KG',33,9),(18,'ARROZ','ALIMENTOS','UP CEREAIS','KG',30,86),(19,'PAPEL HIGIÊNICO','DESCARTÁVEIS','DESCARTÁVEIS GBM','UN',30,4),(20,'CALABRESA DALIA','CARNES','UP','KG',30,40),(21,'BOBINA IMPRESSORA','OUTROS','UP','UN',30,48),(22,'ÓLEO','CONDIMENTOS E TEMPEROS','UP CEREAIS','UN',23,84),(23,'FARINHA BRANCA','ALIMENTOS','UP CEREAIS','KG',23,40),(24,'MACARRÃO','ALIMENTOS','UP CEREAIS','KG',3,67),(25,'SAL FINO','CONDIMENTOS E TEMPEROS','UP CEREAIS','KG',23,25),(26,'REPOLHO','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',21,4.8),(27,'MACAXEIRA','ALIMENTOS','MACAXEIRA GBM','KG',15,35),(28,'SABÃO PÓ','LIMPEZA','VERDURAS GBM','PCT',12,0),(29,'GUARDANAPO','DESCARTÁVEIS','UP','PCT',23,20),(30,'POLIDOR ALUMINIO','LIMPEZA','UP','L',12,8),(31,'BATATA FRITA','ALIMENTOS','UP','PCT',6,52),(32,'CARNE DE SOL','CARNES','VAN CARNES GBM','KG',8.328,24),(33,'PALITO DE DENTE','DESCARTÁVEIS','UP','UN',12,1.1),(34,'MAMINHA','CARNES','UP','KG',7.536,70),(35,'CREME DE LEITE LECO','ALIMENTOS','UP','UN',10,7),(36,'CANUDINHO','DESCARTÁVEIS','UP','UN',10,0),(37,'FEIJÃO CARIOCA','ALIMENTOS','UP CEREAIS','KG',9,34),(38,'VEJA','CONDIMENTOS E TEMPEROS','VERDURAS GBM','UN',9,8),(39,'PICANHA SUÍNA','CARNES','UP','KG',6.058,0),(40,'PICANHA','CARNES','UP','KG',6.448,8),(41,'FILE PEITO FRANGO','CARNES','VAGNER GBM','KG',9.214,0),(42,'AÇÚCAR','ALIMENTOS','UP CEREAIS','KG',8,8),(43,'CARVÃO','OUTROS','TACIANO GBM','PCT',7,9),(44,'AZEITONA PCT PEQUENO','ALIMENTOS','TEMPERO E MOLHO GBM','UN',6,4.8),(45,'CHUCHU','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',6,16),(46,'MANTA CARNEIRO','OUTROS','VAN CARNES GBM','KG',5.334,0),(47,'FEIJÃO PRETO','ALIMENTOS','UP CEREAIS','KG',5,10),(48,'MOLHO INGLÊS','CONDIMENTOS E TEMPEROS','UP','L',5,0),(49,'PIM DE CHEIRO','CONDIMENTOS E TEMPEROS','VERDURAS GBM','PORCAO',0,0.88),(50,'DETERGENTE LÍQUIDO','DESCARTÁVEIS','UP','UN',1,4),(51,'SABONETE LÍQUIDO','HIGIENE','UP','L',5,1),(52,'DESINFETANTE','LIMPEZA','UP','L',5,0),(53,'LEITE LÍQUIDO','ALIMENTOS','UP','L',3,10),(54,'MARGARINA BALDE 15KG','ALIMENTOS','UP TEMPEROS E MOLHOS','UN',3,2),(55,'AZEITE','CONDIMENTOS E TEMPEROS','UP','L',4,1),(56,'MOLHO MADEIRA','CONDIMENTOS E TEMPEROS','TEMPERO E MOLHO GBM','UN',4,5.5),(57,'COPO DESC','DESCARTÁVEIS','UP','PCT',6,11),(58,'BUCHA PRATO','LIMPEZA','UP','UN',4,1.125),(59,'SABÃO PEDRA','LIMPEZA','UP','PCT',2,16),(60,'CALABRESA FRANGO','CARNES','VAGNER GBM','KG',3.546,4.5),(61,'CHARQUE','CARNES','VAGNER GBM','KG',2.924,5),(62,'FILÉ MIGNON','CARNES','VAN CARNES GBM','KG',3.338,7.5),(63,'COLORAU','CONDIMENTOS E TEMPEROS','VERDURAS GBM','KG',3,3.04),(64,'GARFO','DESCARTÁVEIS','UP','PCT',3,1.54),(65,'BOBINA G','OUTROS','UP','UN',1,7.7),(66,'FACA','OUTROS','UP','PCT',3,1.571),(67,'ABÓBORAS','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',3,0.8),(68,'BATATA INGLESA','VEGETAIS E FRUTAS','VERDURAS GBM','SC',2,8),(69,'VINAGRE','CONDIMENTOS E TEMPEROS','VERDURAS GBM','UN',2,8),(70,'CAMARÃO','CARNES','VINICIUS / GALEGA GBM','KG',1,3.55),(71,'DUETO MILHO E ERVILHA','ALIMENTOS','UP TEMPEROS E MOLHOS','UN',2,0.95),(72,'PÃO DE CHARQUE','ALIMENTOS','PÃO DE ALHO GBM','UN',3,4),(73,'CAFÉ EM PÓ','BEBIDAS','TEMPERO E MOLHO GBM','PCT',1,5),(74,'BARBECUE','CONDIMENTOS E TEMPEROS','UP TEMPEROS E MOLHOS','UN',1,5),(75,'SACOLA BRANCA','CONDIMENTOS E TEMPEROS','UP','PCT',2,1.54),(76,'PAPEL FILME','DESCARTÁVEIS','UP','UN',2,2.75),(77,'SACO DE LIXO G','DESCARTÁVEIS','UP','SC',3,36),(78,'AMACIANTE','LIMPEZA','UP','UN',1,2.5),(79,'CLORO/ÁGUA SANIT','LIMPEZA','VERDURAS GBM','UN',0,4),(80,'BOBINA M','OUTROS','UP','UN',2,6.9),(81,'COLHER','OUTROS','UP','UN',3,4.25),(82,'N7 ALUMÍNIO','OUTROS','UP','CX',2,0),(83,'COENTRO','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',1,24),(84,'ORÉGANO','CONDIMENTOS E TEMPEROS','VERDURAS GBM','KG',1.446,0.8),(85,'TILÁPIA','VEGETAIS E FRUTAS','UP','KG',0,10),(86,'PRESUNTO','ALIMENTOS','UP','KG',1,1.005),(87,'CALDO DE GALINHA','ALIMENTOS','UP','UN',1,3.5),(88,'PÃO DE ALHO','ALIMENTOS','PÃO DE ALHO GBM','UN',0,18),(89,'PARMESÃO RALADO','ALIMENTOS','UP','PCT',0,10),(90,'ÁLCOOL','BEBIDAS','UP','UN',1,2),(91,'EXTRATO DE TOMATE GRANDE','CONDIMENTOS E TEMPEROS','UP','UN',0,2.857),(92,'KETCHUP GRANDE','CONDIMENTOS E TEMPEROS','UP TEMPEROS E MOLHOS','UN',1,1),(93,'MOSTARDA GARRAFA 3 kG','CONDIMENTOS E TEMPEROS','UP','UN',1,1),(94,'SACO DE LIXO P','DESCARTÁVEIS','UP','SC',1,0),(95,'LUVA DESCARTAVEL','HIGIENE','UP','PCT',1,1.6),(96,'TOMATE','LIMPEZA','VERDURAS GBM','CX',1,1),(97,'N8 ALUMÍNIO','OUTROS','UP','CX',1,0),(98,'ALFACE','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',1,3),(99,'ALHO','VEGETAIS E FRUTAS','VERDURAS GBM','CX',1,1),(100,'BETERRABA','VEGETAIS E FRUTAS','VERDURAS GBM','UN',0,3.2),(101,'CHAMPÍON','VEGETAIS E FRUTAS','TEMPERO E MOLHO GBM','KG',0.96,1),(102,'FÍGADO','CARNES','UP','KG',0.866,0),(103,'BISTECA SUÍNA','CARNES','VAN CARNES GBM','KG',0,4),(104,'GALETO DESOSSADO','CARNES','VAGNER GBM','UN',0,73),(105,'LOURO','CONDIMENTOS E TEMPEROS','VERDURAS GBM','KG',0.428,1.6),(106,'CALDO DE CARNE','ALIMENTOS','UP','UN',0,3.5),(107,'CHAMBARIL','ALIMENTOS','VAN CARNES GBM','KG',0,5),(108,'FARINHA DE TRIGO','ALIMENTOS','UP','KG',0,2.5),(109,'FARINHA ROSCA','ALIMENTOS','UP','KG',0,2),(110,'LEITE PÓ','ALIMENTOS','UP','PCT',0,0),(111,'MUSSARELA','ALIMENTOS','UP','KG',0.596,2),(112,'OVOS','ALIMENTOS','VERDURAS GBM','BANDEJA',0,8),(113,'CARNE MOÍDA','CARNES','UP','KG',0,6),(114,'GALETO CARCAÇA','CARNES','VAGNER GBM','CX',0,43.7),(115,'GALINHA','CARNES','UP','KG',0,10),(116,'PICADINHO / BOI GUISADO','CARNES','VAN CARNES GBM','KG',0,5),(117,'TEMPERO','CARNES','VERDURAS GBM','KG',0,1),(118,'SAL GROSSO','CONDIMENTOS E TEMPEROS','UP CEREAIS','KG',9,17),(119,'PAPEL TOALHA','DESCARTÁVEIS','DESCARTÁVEIS GBM','UN',0,16),(120,'BOMBRIL','LIMPEZA','VERDURAS GBM','PCT',4,6.75),(121,'FLANELA','LIMPEZA','VERDURAS GBM','UN',0,2),(122,'PANO DE CHÃO','LIMPEZA','VERDURAS GBM','UN',0,0),(123,'PANO DE PRATO','LIMPEZA','VERDURAS GBM','UN',0,0),(124,'BOBINA P','OUTROS','UP','UN',3,3.3),(125,'SALSA','OUTROS','VERDURAS GBM','PORCAO',0,7),(126,'CEBOLA','VEGETAIS E FRUTAS','VERDURAS GBM','UN',0,1.18),(127,'CENOURAS','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',0,20),(128,'PIMENTÃO','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',2,32),(129,'PUDIM','SOBREMESA','HÉLIO OU LE PUDIM','PORCAO',0,44),(130,'FILÉ PEITO DE FRANGO PRODUZIDO','CARNES','UP','KG',3.6,8),(131,'LIMÃO','VEGETAIS E FRUTAS','VERDURAS GBM','KG',3.6,15),(132,'GARRAFAS 300 ML','DESCARTÁVEIS','UP','KG',3.6,85),(133,'LARANJA P/ SUCO','VEGETAIS E FRUTAS','VERDURAS GBM','KG',3.6,2.5),(134,'COP','VEGETAIS E FRUTAS','VERDURAS GBM','KG',3.6,0),(200,'BOBINA GG','DESCARTÁVEIS','DESCARTÁVEIS GBM','UN',2,0),(201,'DESENGORDURANTE','LIMPEZA','UP','UN',0,0),(202,'PERFEX','LIMPEZA','UP','ROLO',0,0),(203,'COPO DE CAFÉ','DESCARTÁVEIS','DESCARTÁVEIS GBM','PCT',0,0.9),(204,'PASSAS','CONDIMENTOS E TEMPEROS','TEMPERO E MOLHO GBM','KG',0,1)
),
c as (insert into public.categories (name) select distinct category from raw on conflict (name) do nothing returning 1),
s as (insert into public.suppliers (name) select distinct supplier from raw on conflict (name) do nothing returning 1)
select 1;

insert into public.products (code, description, category_id, supplier_id, unit, current_stock, avg_weekly_consumption, min_stock, desired_stock)
select r.code, r.description, cat.id, sup.id, r.unit, r.stock, r.consumption, r.consumption,
       case when r.consumption > 0 then r.consumption * 2 else r.stock end
from (values
(1,'TAMPAS DE POTE','CONDIMENTOS E TEMPEROS','UP','UN',4000,825),(2,'SACO VINAGRETE','DESCARTÁVEIS','UP','UN',1000,2600),(3,'SACO TROCO','DESCARTÁVEIS','UP','UN',1000,1100),(4,'TAMPA M32','OUTROS','UP','UN',900,260),(5,'CALABRESA CHARQUE','CARNES','UP','KG',0,6.6),(6,'M65','OUTROS','UP','UN',400,400),(7,'H3','OUTROS','UP','UN',300,550),(8,'M32','OUTROS','UP','UN',300,260),(9,'M50','OUTROS','UP','UN',400,900),(10,'M500','OUTROS','UP','UN',300,400),(11,'TAMPA M500','OUTROS','UP','UN',250,400),(12,'POTE MAIONESE','DESCARTÁVEIS','UP','UN',50,825),(13,'H2','OUTROS','UP','UN',100,550),(14,'H5','OUTROS','DESCARTÁVEIS GBM','UN',50,275),(15,'GALETOS CORTADOS','CARNES','VAGNER GBM','UN',30,310),(16,'PRATO DESCARTAVEL','DESCARTÁVEIS','UP','UN',43,0),(17,'FEIJÃO TROPEIRO','ALIMENTOS','UP CEREAIS','KG',33,9),(18,'ARROZ','ALIMENTOS','UP CEREAIS','KG',30,86),(19,'PAPEL HIGIÊNICO','DESCARTÁVEIS','DESCARTÁVEIS GBM','UN',30,4),(20,'CALABRESA DALIA','CARNES','UP','KG',30,40),(21,'BOBINA IMPRESSORA','OUTROS','UP','UN',30,48),(22,'ÓLEO','CONDIMENTOS E TEMPEROS','UP CEREAIS','UN',23,84),(23,'FARINHA BRANCA','ALIMENTOS','UP CEREAIS','KG',23,40),(24,'MACARRÃO','ALIMENTOS','UP CEREAIS','KG',3,67),(25,'SAL FINO','CONDIMENTOS E TEMPEROS','UP CEREAIS','KG',23,25),(26,'REPOLHO','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',21,4.8),(27,'MACAXEIRA','ALIMENTOS','MACAXEIRA GBM','KG',15,35),(28,'SABÃO PÓ','LIMPEZA','VERDURAS GBM','PCT',12,0),(29,'GUARDANAPO','DESCARTÁVEIS','UP','PCT',23,20),(30,'POLIDOR ALUMINIO','LIMPEZA','UP','L',12,8),(31,'BATATA FRITA','ALIMENTOS','UP','PCT',6,52),(32,'CARNE DE SOL','CARNES','VAN CARNES GBM','KG',8.328,24),(33,'PALITO DE DENTE','DESCARTÁVEIS','UP','UN',12,1.1),(34,'MAMINHA','CARNES','UP','KG',7.536,70),(35,'CREME DE LEITE LECO','ALIMENTOS','UP','UN',10,7),(36,'CANUDINHO','DESCARTÁVEIS','UP','UN',10,0),(37,'FEIJÃO CARIOCA','ALIMENTOS','UP CEREAIS','KG',9,34),(38,'VEJA','CONDIMENTOS E TEMPEROS','VERDURAS GBM','UN',9,8),(39,'PICANHA SUÍNA','CARNES','UP','KG',6.058,0),(40,'PICANHA','CARNES','UP','KG',6.448,8),(41,'FILE PEITO FRANGO','CARNES','VAGNER GBM','KG',9.214,0),(42,'AÇÚCAR','ALIMENTOS','UP CEREAIS','KG',8,8),(43,'CARVÃO','OUTROS','TACIANO GBM','PCT',7,9),(44,'AZEITONA PCT PEQUENO','ALIMENTOS','TEMPERO E MOLHO GBM','UN',6,4.8),(45,'CHUCHU','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',6,16),(46,'MANTA CARNEIRO','OUTROS','VAN CARNES GBM','KG',5.334,0),(47,'FEIJÃO PRETO','ALIMENTOS','UP CEREAIS','KG',5,10),(48,'MOLHO INGLÊS','CONDIMENTOS E TEMPEROS','UP','L',5,0),(49,'PIM DE CHEIRO','CONDIMENTOS E TEMPEROS','VERDURAS GBM','PORCAO',0,0.88),(50,'DETERGENTE LÍQUIDO','DESCARTÁVEIS','UP','UN',1,4),(51,'SABONETE LÍQUIDO','HIGIENE','UP','L',5,1),(52,'DESINFETANTE','LIMPEZA','UP','L',5,0),(53,'LEITE LÍQUIDO','ALIMENTOS','UP','L',3,10),(54,'MARGARINA BALDE 15KG','ALIMENTOS','UP TEMPEROS E MOLHOS','UN',3,2),(55,'AZEITE','CONDIMENTOS E TEMPEROS','UP','L',4,1),(56,'MOLHO MADEIRA','CONDIMENTOS E TEMPEROS','TEMPERO E MOLHO GBM','UN',4,5.5),(57,'COPO DESC','DESCARTÁVEIS','UP','PCT',6,11),(58,'BUCHA PRATO','LIMPEZA','UP','UN',4,1.125),(59,'SABÃO PEDRA','LIMPEZA','UP','PCT',2,16),(60,'CALABRESA FRANGO','CARNES','VAGNER GBM','KG',3.546,4.5),(61,'CHARQUE','CARNES','VAGNER GBM','KG',2.924,5),(62,'FILÉ MIGNON','CARNES','VAN CARNES GBM','KG',3.338,7.5),(63,'COLORAU','CONDIMENTOS E TEMPEROS','VERDURAS GBM','KG',3,3.04),(64,'GARFO','DESCARTÁVEIS','UP','PCT',3,1.54),(65,'BOBINA G','OUTROS','UP','UN',1,7.7),(66,'FACA','OUTROS','UP','PCT',3,1.571),(67,'ABÓBORAS','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',3,0.8),(68,'BATATA INGLESA','VEGETAIS E FRUTAS','VERDURAS GBM','SC',2,8),(69,'VINAGRE','CONDIMENTOS E TEMPEROS','VERDURAS GBM','UN',2,8),(70,'CAMARÃO','CARNES','VINICIUS / GALEGA GBM','KG',1,3.55),(71,'DUETO MILHO E ERVILHA','ALIMENTOS','UP TEMPEROS E MOLHOS','UN',2,0.95),(72,'PÃO DE CHARQUE','ALIMENTOS','PÃO DE ALHO GBM','UN',3,4),(73,'CAFÉ EM PÓ','BEBIDAS','TEMPERO E MOLHO GBM','PCT',1,5),(74,'BARBECUE','CONDIMENTOS E TEMPEROS','UP TEMPEROS E MOLHOS','UN',1,5),(75,'SACOLA BRANCA','CONDIMENTOS E TEMPEROS','UP','PCT',2,1.54),(76,'PAPEL FILME','DESCARTÁVEIS','UP','UN',2,2.75),(77,'SACO DE LIXO G','DESCARTÁVEIS','UP','SC',3,36),(78,'AMACIANTE','LIMPEZA','UP','UN',1,2.5),(79,'CLORO/ÁGUA SANIT','LIMPEZA','VERDURAS GBM','UN',0,4),(80,'BOBINA M','OUTROS','UP','UN',2,6.9),(81,'COLHER','OUTROS','UP','UN',3,4.25),(82,'N7 ALUMÍNIO','OUTROS','UP','CX',2,0),(83,'COENTRO','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',1,24),(84,'ORÉGANO','CONDIMENTOS E TEMPEROS','VERDURAS GBM','KG',1.446,0.8),(85,'TILÁPIA','VEGETAIS E FRUTAS','UP','KG',0,10),(86,'PRESUNTO','ALIMENTOS','UP','KG',1,1.005),(87,'CALDO DE GALINHA','ALIMENTOS','UP','UN',1,3.5),(88,'PÃO DE ALHO','ALIMENTOS','PÃO DE ALHO GBM','UN',0,18),(89,'PARMESÃO RALADO','ALIMENTOS','UP','PCT',0,10),(90,'ÁLCOOL','BEBIDAS','UP','UN',1,2),(91,'EXTRATO DE TOMATE GRANDE','CONDIMENTOS E TEMPEROS','UP','UN',0,2.857),(92,'KETCHUP GRANDE','CONDIMENTOS E TEMPEROS','UP TEMPEROS E MOLHOS','UN',1,1),(93,'MOSTARDA GARRAFA 3 kG','CONDIMENTOS E TEMPEROS','UP','UN',1,1),(94,'SACO DE LIXO P','DESCARTÁVEIS','UP','SC',1,0),(95,'LUVA DESCARTAVEL','HIGIENE','UP','PCT',1,1.6),(96,'TOMATE','LIMPEZA','VERDURAS GBM','CX',1,1),(97,'N8 ALUMÍNIO','OUTROS','UP','CX',1,0),(98,'ALFACE','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',1,3),(99,'ALHO','VEGETAIS E FRUTAS','VERDURAS GBM','CX',1,1),(100,'BETERRABA','VEGETAIS E FRUTAS','VERDURAS GBM','UN',0,3.2),(101,'CHAMPÍON','VEGETAIS E FRUTAS','TEMPERO E MOLHO GBM','KG',0.96,1),(102,'FÍGADO','CARNES','UP','KG',0.866,0),(103,'BISTECA SUÍNA','CARNES','VAN CARNES GBM','KG',0,4),(104,'GALETO DESOSSADO','CARNES','VAGNER GBM','UN',0,73),(105,'LOURO','CONDIMENTOS E TEMPEROS','VERDURAS GBM','KG',0.428,1.6),(106,'CALDO DE CARNE','ALIMENTOS','UP','UN',0,3.5),(107,'CHAMBARIL','ALIMENTOS','VAN CARNES GBM','KG',0,5),(108,'FARINHA DE TRIGO','ALIMENTOS','UP','KG',0,2.5),(109,'FARINHA ROSCA','ALIMENTOS','UP','KG',0,2),(110,'LEITE PÓ','ALIMENTOS','UP','PCT',0,0),(111,'MUSSARELA','ALIMENTOS','UP','KG',0.596,2),(112,'OVOS','ALIMENTOS','VERDURAS GBM','BANDEJA',0,8),(113,'CARNE MOÍDA','CARNES','UP','KG',0,6),(114,'GALETO CARCAÇA','CARNES','VAGNER GBM','CX',0,43.7),(115,'GALINHA','CARNES','UP','KG',0,10),(116,'PICADINHO / BOI GUISADO','CARNES','VAN CARNES GBM','KG',0,5),(117,'TEMPERO','CARNES','VERDURAS GBM','KG',0,1),(118,'SAL GROSSO','CONDIMENTOS E TEMPEROS','UP CEREAIS','KG',9,17),(119,'PAPEL TOALHA','DESCARTÁVEIS','DESCARTÁVEIS GBM','UN',0,16),(120,'BOMBRIL','LIMPEZA','VERDURAS GBM','PCT',4,6.75),(121,'FLANELA','LIMPEZA','VERDURAS GBM','UN',0,2),(122,'PANO DE CHÃO','LIMPEZA','VERDURAS GBM','UN',0,0),(123,'PANO DE PRATO','LIMPEZA','VERDURAS GBM','UN',0,0),(124,'BOBINA P','OUTROS','UP','UN',3,3.3),(125,'SALSA','OUTROS','VERDURAS GBM','PORCAO',0,7),(126,'CEBOLA','VEGETAIS E FRUTAS','VERDURAS GBM','UN',0,1.18),(127,'CENOURAS','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',0,20),(128,'PIMENTÃO','VEGETAIS E FRUTAS','VERDURAS GBM','PORCAO',2,32),(129,'PUDIM','SOBREMESA','HÉLIO OU LE PUDIM','PORCAO',0,44),(130,'FILÉ PEITO DE FRANGO PRODUZIDO','CARNES','UP','KG',3.6,8),(131,'LIMÃO','VEGETAIS E FRUTAS','VERDURAS GBM','KG',3.6,15),(132,'GARRAFAS 300 ML','DESCARTÁVEIS','UP','KG',3.6,85),(133,'LARANJA P/ SUCO','VEGETAIS E FRUTAS','VERDURAS GBM','KG',3.6,2.5),(134,'COP','VEGETAIS E FRUTAS','VERDURAS GBM','KG',3.6,0),(200,'BOBINA GG','DESCARTÁVEIS','DESCARTÁVEIS GBM','UN',2,0),(201,'DESENGORDURANTE','LIMPEZA','UP','UN',0,0),(202,'PERFEX','LIMPEZA','UP','ROLO',0,0),(203,'COPO DE CAFÉ','DESCARTÁVEIS','DESCARTÁVEIS GBM','PCT',0,0.9),(204,'PASSAS','CONDIMENTOS E TEMPEROS','TEMPERO E MOLHO GBM','KG',0,1)
) as r(code, description, category, supplier, unit, stock, consumption)
join public.categories cat on cat.name = r.category
join public.suppliers sup on sup.name = r.supplier
on conflict (code) do nothing;

insert into public.stock_movements (product_id, type, quantity_before, quantity_change, quantity_after, user_name, notes)
select id, 'contagem', 0, current_stock, current_stock, 'Importação', 'Carga inicial da planilha'
from public.products;